import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Personalización de Contenidos y Textos',
  type: 'document',
  groups: [
    { name: 'general', title: '1. Contacto y Redes' },
    { name: 'hero', title: '2. Portada / Hero' },
    { name: 'brands', title: '3. Sección Marcas' },
    { name: 'factory', title: '4. Fábrica y Talleres' },
    { name: 'distributor', title: '5. Distribuidores' },
    { name: 'lookbook', title: '6. Portafolio / Prendas' },
    { name: 'catalogs', title: '7. Descarga de Catálogos' },
    { name: 'quote', title: '8. Cotizador B2B' },
  ],
  fields: [
    // ----------------- GRUPO 1: GENERAL & CONTACTO -----------------
    defineField({
      name: 'companyName',
      title: 'Nombre de Empresa',
      type: 'string',
      group: 'general',
      initialValue: 'JHONAL 80',
    }),
    defineField({
      name: 'announcementText',
      title: 'Texto de la Barra Superior de Anuncios',
      type: 'string',
      group: 'general',
      initialValue: 'Catálogos 2026 Disponibles - Atención a distribuidores y mayoristas',
    }),
    defineField({
      name: 'whatsappNumber',
      title: 'Número de WhatsApp (con código de país sin +)',
      type: 'string',
      group: 'general',
      description: 'Ej: 573001234567 para Colombia',
      initialValue: '573000000000',
    }),
    defineField({
      name: 'generalPhone',
      title: 'Teléfono Fijo o Celular de Contacto',
      type: 'string',
      group: 'general',
      initialValue: '+57 (300) 000-0000',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Correo Electrónico de Contacto',
      type: 'string',
      group: 'general',
      initialValue: 'contacto@jhonal80.com',
    }),
    defineField({
      name: 'address',
      title: 'Dirección o Ciudad Principal',
      type: 'string',
      group: 'general',
      initialValue: 'Medellín / Colombia • Despachos a todo el país',
    }),
    defineField({
      name: 'instagramUrl',
      title: 'URL Instagram',
      type: 'url',
      group: 'general',
      initialValue: 'https://www.instagram.com/jhonal.80/',
    }),
    defineField({
      name: 'facebookUrl',
      title: 'URL Facebook',
      type: 'url',
      group: 'general',
      initialValue: 'https://www.facebook.com/p/Jhonal80-100091825447640/',
    }),

    // ----------------- GRUPO 2: HERO / PORTADA -----------------
    defineField({
      name: 'heroBadge',
      title: 'Distintivo Superior (Badge)',
      type: 'string',
      group: 'hero',
      initialValue: 'Confección y diseño 100% colombiano • Desde 2007',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Título Principal del Hero',
      type: 'string',
      group: 'hero',
      initialValue: 'Fabricamos moda que impulsa tus ventas',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Subtítulo / Descripción del Hero',
      type: 'text',
      rows: 2,
      group: 'hero',
      initialValue: '18 años de experiencia en confección colombiana al servicio de tu negocio.',
    }),
    defineField({
      name: 'heroCtaPrimaryText',
      title: 'Texto Botón Principal',
      type: 'string',
      group: 'hero',
      initialValue: 'Solicitar Cotización por Mayor',
    }),
    defineField({
      name: 'heroCtaSecondaryText',
      title: 'Texto Botón Secundario',
      type: 'string',
      group: 'hero',
      initialValue: 'Ver Catálogos Digitales',
    }),
    // 4 Value Cards del Hero
    defineField({
      name: 'heroCard1Title',
      title: 'Tarjeta 1 - Título',
      type: 'string',
      group: 'hero',
      initialValue: 'Precios de Fábrica',
    }),
    defineField({
      name: 'heroCard1Desc',
      title: 'Tarjeta 1 - Subtítulo',
      type: 'string',
      group: 'hero',
      initialValue: 'Márgenes de ganancia para tu negocio',
    }),
    defineField({
      name: 'heroCard2Title',
      title: 'Tarjeta 2 - Título',
      type: 'string',
      group: 'hero',
      initialValue: '4 Marcas en 1 Pedido',
    }),
    defineField({
      name: 'heroCard2Desc',
      title: 'Tarjeta 2 - Subtítulo',
      type: 'string',
      group: 'hero',
      initialValue: 'Fénix, Romper, Jhonal y Lady\'s',
    }),
    defineField({
      name: 'heroCard3Title',
      title: 'Tarjeta 3 - Título',
      type: 'string',
      group: 'hero',
      initialValue: 'Despachos Nacionales',
    }),
    defineField({
      name: 'heroCard3Desc',
      title: 'Tarjeta 3 - Subtítulo',
      type: 'string',
      group: 'hero',
      initialValue: 'Envíos seguros a toda Colombia',
    }),
    defineField({
      name: 'heroCard4Title',
      title: 'Tarjeta 4 - Título',
      type: 'string',
      group: 'hero',
      initialValue: 'Garantía Total',
    }),
    defineField({
      name: 'heroCard4Desc',
      title: 'Tarjeta 4 - Subtítulo',
      type: 'string',
      group: 'hero',
      initialValue: 'Telas y confección certificada',
    }),

    // ----------------- GRUPO 3: SECCIÓN MARCAS -----------------
    defineField({
      name: 'brandsBadge',
      title: 'Distintivo de Marcas (Badge)',
      type: 'string',
      group: 'brands',
      initialValue: 'Nuestras 4 marcas',
    }),
    defineField({
      name: 'brandsTitle',
      title: 'Título de la Sección de Marcas',
      type: 'string',
      group: 'brands',
      initialValue: 'Ropa pensada para rotar y vender todos los días',
    }),
    defineField({
      name: 'brandsDescription',
      title: 'Descripción de la Sección de Marcas',
      type: 'text',
      rows: 2,
      group: 'brands',
      initialValue: 'Cada marca tiene su propio estilo para que puedas ofrecerle a tus clientes justo lo que están buscando, con excelente confección y telas garantizadas.',
    }),

    // ----------------- GRUPO 4: FÁBRICA Y TALLERES -----------------
    defineField({
      name: 'factoryBadge',
      title: 'Distintivo de Fábrica (Badge)',
      type: 'string',
      group: 'factory',
      initialValue: 'Nuestra fábrica y talleres',
    }),
    defineField({
      name: 'factoryTitle',
      title: 'Título de Fábrica',
      type: 'string',
      group: 'factory',
      initialValue: 'Más de 17 años vistiendo a Colombia con confección de verdad',
    }),
    defineField({
      name: 'factoryParagraph1',
      title: 'Párrafo 1 (Historia/Propósito)',
      type: 'text',
      rows: 2,
      group: 'factory',
      initialValue: 'En Jhonal 80 nacimos en 2007 con un objetivo muy claro: fabricar ropa con excelente horma, telas garantizadas y diseños que realmente roten rápido en los mostradores.',
    }),
    defineField({
      name: 'factoryParagraph2',
      title: 'Párrafo 2 (Proceso/Taller)',
      type: 'text',
      rows: 3,
      group: 'factory',
      initialValue: 'Contamos con planta física propia, talleres de estampado en serigrafía, mesas de corte y un equipo humano calificado. No somos intermediarios: controlamos todo el proceso desde el corte de la tela hasta el empaque final para entregarte calidad constante y precios directos de fábrica.',
    }),
    // 3 Métricas de Fábrica
    defineField({
      name: 'factoryStat1Number',
      title: 'Métrica 1 - Número/Valor',
      type: 'string',
      group: 'factory',
      initialValue: '+17 años',
    }),
    defineField({
      name: 'factoryStat1Label',
      title: 'Métrica 1 - Título',
      type: 'string',
      group: 'factory',
      initialValue: 'Experiencia',
    }),
    defineField({
      name: 'factoryStat1Desc',
      title: 'Métrica 1 - Descripción',
      type: 'string',
      group: 'factory',
      initialValue: 'Tradición y solidez en el mercado textil',
    }),
    defineField({
      name: 'factoryStat2Number',
      title: 'Métrica 2 - Número/Valor',
      type: 'string',
      group: 'factory',
      initialValue: '100%',
    }),
    defineField({
      name: 'factoryStat2Label',
      title: 'Métrica 2 - Título',
      type: 'string',
      group: 'factory',
      initialValue: 'Hecho en Colombia',
    }),
    defineField({
      name: 'factoryStat2Desc',
      title: 'Métrica 2 - Descripción',
      type: 'string',
      group: 'factory',
      initialValue: 'Mano de obra y confección nacional',
    }),
    defineField({
      name: 'factoryStat3Number',
      title: 'Métrica 3 - Número/Valor',
      type: 'string',
      group: 'factory',
      initialValue: 'Directo',
    }),
    defineField({
      name: 'factoryStat3Label',
      title: 'Métrica 3 - Título',
      type: 'string',
      group: 'factory',
      initialValue: 'De fábrica',
    }),
    defineField({
      name: 'factoryStat3Desc',
      title: 'Métrica 3 - Descripción',
      type: 'string',
      group: 'factory',
      initialValue: 'Sin sobrecostos ni terceros',
    }),
    // Fotos y Video de Fábrica
    defineField({
      name: 'factoryPhoto1',
      title: 'Foto 1 de Planta (Mesa de corte / Estampado)',
      type: 'image',
      group: 'factory',
      options: { hotspot: true },
    }),
    defineField({
      name: 'factoryPhoto1Title',
      title: 'Foto 1 - Título',
      type: 'string',
      group: 'factory',
      initialValue: 'Talleres de serigrafía y estampado',
    }),
    defineField({
      name: 'factoryPhoto1Subtitle',
      title: 'Foto 1 - Subtítulo',
      type: 'string',
      group: 'factory',
      initialValue: 'Pulpos de impresión textil y mesas de corte de alto volumen',
    }),
    defineField({
      name: 'factoryPhoto2',
      title: 'Foto 2 de Planta (Confección / Empaque)',
      type: 'image',
      group: 'factory',
      options: { hotspot: true },
    }),
    defineField({
      name: 'factoryPhoto2Title',
      title: 'Foto 2 - Título',
      type: 'string',
      group: 'factory',
      initialValue: 'Área de confección y empaque',
    }),
    defineField({
      name: 'factoryPhoto2Subtitle',
      title: 'Foto 2 - Subtítulo',
      type: 'string',
      group: 'factory',
      initialValue: 'Revisión prenda por prenda',
    }),
    defineField({
      name: 'factoryVideoFile',
      title: 'Archivo de Video de Fábrica (MP4)',
      type: 'file',
      group: 'factory',
      description: 'Sube un video MP4 grabado en los talleres o planta',
    }),

    // ----------------- GRUPO 5: DISTRIBUIDORES -----------------
    defineField({
      name: 'distributorBadge',
      title: 'Distintivo Distribuidores (Badge)',
      type: 'string',
      group: 'distributor',
      initialValue: 'Gana con nosotros',
    }),
    defineField({
      name: 'distributorTitle',
      title: 'Título Sección Distribuidores',
      type: 'string',
      group: 'distributor',
      initialValue: 'Conviértete en distribuidor de Jhonal.80',
    }),
    defineField({
      name: 'distributorDescription',
      title: 'Descripción Distribuidores',
      type: 'text',
      rows: 2,
      group: 'distributor',
      initialValue: 'Accede a precios directos de fábrica, acompañamiento comercial constante y un portafolio de 4 marcas diseñadas para rotar rápido.',
    }),
    defineField({
      name: 'distributorBannerQuote',
      title: 'Texto Frase Destacada (Quote Banner)',
      type: 'text',
      rows: 2,
      group: 'distributor',
      initialValue: '“Buscamos aliados comerciales a largo plazo. Si tu negocio crece, nosotros crecemos contigo.”',
    }),

    // ----------------- GRUPO 6: PORTAFOLIO / LOOKBOOK -----------------
    defineField({
      name: 'lookbookBadge',
      title: 'Distintivo Portafolio (Badge)',
      type: 'string',
      group: 'lookbook',
      initialValue: 'Portafolio de Prendas',
    }),
    defineField({
      name: 'lookbookTitle',
      title: 'Título Portafolio',
      type: 'string',
      group: 'lookbook',
      initialValue: 'Explora nuestras colecciones por marca',
    }),
    defineField({
      name: 'lookbookDescription',
      title: 'Descripción Portafolio',
      type: 'text',
      rows: 2,
      group: 'lookbook',
      initialValue: 'Filtra por marca o tipo de prenda para descubrir los diseños, composiciones y colores listos para despacho mayorista.',
    }),

    // ----------------- GRUPO 7: CATÁLOGOS PDF -----------------
    defineField({
      name: 'catalogsBadge',
      title: 'Distintivo Catálogos (Badge)',
      type: 'string',
      group: 'catalogs',
      initialValue: 'Material descargable',
    }),
    defineField({
      name: 'catalogsTitle',
      title: 'Título Catálogos',
      type: 'string',
      group: 'catalogs',
      initialValue: 'Descarga los catálogos completos en PDF',
    }),
    defineField({
      name: 'catalogsDescription',
      title: 'Descripción Catálogos',
      type: 'text',
      rows: 2,
      group: 'catalogs',
      initialValue: 'Ten a mano las referencias completas, tablas de medidas y variantes de color de cada una de nuestras líneas para compartir con tus clientes.',
    }),

    // ----------------- GRUPO 8: COTIZADOR B2B -----------------
    defineField({
      name: 'quoteBadge',
      title: 'Distintivo Cotizador (Badge)',
      type: 'string',
      group: 'quote',
      initialValue: 'Atención personalizada',
    }),
    defineField({
      name: 'quoteTitle',
      title: 'Título Cotizador B2B',
      type: 'string',
      group: 'quote',
      initialValue: 'Arma tu solicitud de cotización mayorista',
    }),
    defineField({
      name: 'quoteDescription',
      title: 'Descripción Cotizador B2B',
      type: 'text',
      rows: 2,
      group: 'quote',
      initialValue: 'Selecciona las marcas y volúmenes de tu interés. Te responderemos por WhatsApp con precios de fábrica, tiempos de despacho y condiciones comerciales.',
    }),
  ],
})

